// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGdx2cgwT8id5zLsbDRCJwHJJm-9hQd8',
    appId: '1:1075652152028:web:72eaabac482b084c5fc219',
    messagingSenderId: '1075652152028',
    projectId: 'mindease-661f6',
    authDomain: 'mindease-661f6.firebaseapp.com',
    storageBucket: 'mindease-661f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVM6WI8kvRbnPC8b71VXAMwfQuZNMb7Xc',
    appId: '1:1075652152028:android:bbd3c3dc07a70adf5fc219',
    messagingSenderId: '1075652152028',
    projectId: 'mindease-661f6',
    storageBucket: 'mindease-661f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSF1ovt5iZO-LxUR5jHkFQQIk6YuU418',
    appId: '1:1075652152028:ios:70c58a93f4d8afdf5fc219',
    messagingSenderId: '1075652152028',
    projectId: 'mindease-661f6',
    storageBucket: 'mindease-661f6.appspot.com',
    androidClientId: '1075652152028-6673jdbqqv492u192enrvm84frdru4ro.apps.googleusercontent.com',
    iosClientId: '1075652152028-mmth8p2dkknkaefc56b5nfabjdthltpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpadtrialmindease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhSF1ovt5iZO-LxUR5jHkFQQIk6YuU418',
    appId: '1:1075652152028:ios:5232cbf80344ad4a5fc219',
    messagingSenderId: '1075652152028',
    projectId: 'mindease-661f6',
    storageBucket: 'mindease-661f6.appspot.com',
    androidClientId: '1075652152028-6673jdbqqv492u192enrvm84frdru4ro.apps.googleusercontent.com',
    iosClientId: '1075652152028-ufe18qnmeacb6eehui6d0f1c34eij6i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpadtrialmindease.RunnerTests',
  );
}
